- config.yaml
- plugins.yaml
This updates the plugins.yaml and adds the config.yaml to match what we have in the cluster.
> chore: updated plugins/config to match cluster

- config/prow/external-plugins/needs-rebase_deployment.yaml
- config/prow/external-plugins/needs-rebase_service.yaml
- config/prow/kustomization.yaml
```release-note
Add needs rebase external plugin manifests to the prow
```
> Add needs rebase external plugin manifests

- config/prow/external-plugins/cherrypicker_deployment.yaml
- config/prow/external-plugins/needs-rebase_deployment.yaml
- config/prow/plugins.yaml
> fix: various changes for external plugins

- config/prow/plugins.yaml
> chore: added override plugin

- config/prow/plugins.yaml
> Remove duplicate needs rebase

- jobs/test-infra/peribolos/postsubmit.yaml
> chore: changed perobolos to post submit and confirm

- config/prow/org.yaml
> test: small change to test peribolos job

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
```release-note
Add PR/issue templates
```
> Add issue/pr templates

- config/prow/config.yaml
- jobs/rancher-turtles/presubmits.yaml
Fixes #
**Checklist**:
```release-note
Added implementation of rancher-turtles e2e test job using prow installation.
```
> Add and e2e test presubmit job

- config/prow/config.yaml
/kind feature
Fixes #
**Checklist**:
```release-note
Adds merge_method: merge at org level
```
> Update config.yaml with merge_method

- jobs/rancher-turtles/presubmits.yaml
```
0/2 nodes are available: 2 Insufficient cpu. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
```
Getting the following error logs, let's try it without resource requests for now
Test run:
https://prow.calf-nursery.com/view/gs/calf-nursery-prow/pr-logs/pull/calf-nursery_rancher-turtles/3/pull-rancher-turtles-run-e2e/1696189552227520512
Fixes #
**Checklist**:
```release-note
NONE
```
> Update presubmits.yaml for turtles - amend resource requests for now

- config/prow/config.yaml
- jobs/test-infra/branch_protector/periodics.yaml
- jobs/test-infra/label_sync/periodics.yaml
/kind cleanup
Fixes #
**Checklist**:
```release-note
NONE
```
> chore: minor change to jobs and increase history to 24h

- config/prow/config.yaml
Fixes #41 
**Checklist**:
```release-note
Added e2e test artifact display in spyglass using existing bucket
```
> Add gcs variable to link into job artifacts

- config/prow/autobump-config/prow-job-autobump-config.yaml
- config/prow/kustomization.yaml
- config/prow/plugins.yaml
- jobs/test-infra/label_sync/periodics.yaml
Fixes #40
**Checklist**:
```release-note
Add basic autobumper configuration
```
> Add autobump periodic

- config/prow/base/gcsweb.yaml
- config/prow/base/ingress.yaml
- config/prow/base/kustomization.yaml
- config/prow/config.yaml
/kind cleanup
Adding gcsweb deployment and setting it as a default backend for serving artifacts
Fixes #
**Checklist**:
```release-note
Use gcsweb for serving artifacts
```
> Add gcsweb deployment and use it in config

- config/prow/plugins.yaml
Fixes #
**Checklist**:
```release-note
Attempts to fix cherry pick plugin
```
> Attempt to fix cherry pick plugin

- config/prow/org.yaml
/kind bug
Allow squash merge
```release-note
NONE
```
> Allow squash merge

- config/prow/plugins.yaml
/kind feature
Fixes #
**Checklist**:
```release-note
NONE
```
> Enable milestone_applier in repos

- jobs/rancher-turtles/nightly-e2e.yaml
Add new job to run e2e tests in prow.
Fixes #
**Checklist**:
```release-note
```
> test: add e2e test job

- jobs/rancher-turtles/rancher-turtles-nightly-e2e.yaml
Fixes #
**Checklist**:
```release-note
```
> test: update e2e test job name

- jobs/rancher-turtles/rancher-turtles-nightly-e2e.yaml
test: update e2e test job name
Fixes #
**Checklist**:
```release-note
```
> Fix identation in nightly e2e job definition

- jobs/rancher-turtles/rancher-turtles-presubmits-main.yaml
Fixes #
**Checklist**:
```release-note
```
> test: add new environment variable for e2e

- jobs/rancher-turtles/rancher-turtles-presubmits-main.yaml
Fixes #
**Checklist**:
```release-note
```
> test: use only aws creds for e2e

- jobs/rancher-turtles/rancher-turtles-periodics-main.yaml
- jobs/rancher-turtles/rancher-turtles-presubmits-main.yaml
Fixes #
**Checklist**:
```release-note
```
> chore: add new e2e periodic job

- jobs/test-infra/branch_protector/branch_protector_periodics.yaml
- jobs/test-infra/label_sync/label_sync_periodics.yaml
Fixes #
**Checklist**:
```release-note
```
> chore: reduce branch protector and label sync periodicity
